TWILIO_ACCOUNT_SID="<YOUR_ACCOUNT_SID>"
TWILIO_API_KEY="<YOUR_TWILIO_API_KEY>"
TWILIO_API_SECRET="<YOUR_TWILIO_API_SECRET>"

SERVERLESS_DOMAIN="<YOUR_SERVERLESS_DOMAIN>"
SERVERLESS_SID="<YOUR_SERVERLESS_SID>"
SERVERLESS_ENV_SID="<YOUR_SERVERLESS_ENV_SID>"

TWILIO_FLEX_WORKSPACE_SID="<YOUR_TWILIO_FLEX_WORKSPACE_SID>"


